[project]
name = "playwright-browser"
version = "0.1.0"
description = "通过plawright 爬取抖音，微博，X，推特，Instagram等平台"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.3",
    "playwright>=1.58.0",
    "pydash>=8.0.6",
    "rich>=14.3.2",
]
